name: CD

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Extract version from tag
      run: |
        $version = "${{ github.ref }}".replace('refs/tags/v', '')
        echo "PACKAGE_VERSION=$version" >> $env:GITHUB_ENV
    - name: Print PACKAGE_VERSION
      run: echo $env:PACKAGE_VERSION

    # Pack and Publish MVVMToolkitExtensions.WPF
    - name: Pack MyPackage.WPF with tag version
      run: dotnet pack .\src\MVVMToolkitExtensions.WPF\MVVMToolkitExtensions.WPF.csproj --configuration Release -o .\out /p:PackageVersion=${{ env.PACKAGE_VERSION }}

    - name: Push MVVMToolkitExtensions.WPF to NuGet
      run: dotnet nuget push ".\out\MVVMToolkitExtensions.WPF.*.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json

    # Pack and Publish MyPackage.MAUI
    - name: Pack MVVMToolkitExtensions.MAUI with tag version
      run: dotnet pack .\src\MVVMToolkitExtensions.MAUI\MVVMToolkitExtensions.MAUI.csproj --configuration Release -o .\out /p:PackageVersion=${{ env.PACKAGE_VERSION }}

    - name: Push MVVMToolkitExtensions.MAUI to NuGet
      run: dotnet nuget push ".\out\MVVMToolkitExtensions.MAUI.*.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
