name: deployment

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet: ['6.0.x', '7.0.x']
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Extract version from tag
      run: echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/v}" >> $env:GITHUB_ENV 

    - name: Pack with tag version
      run: dotnet pack ./src/MVVMToolkitExtensions.WPF.csproj --configuration Release -o ./out /p:Version=${{ env.PACKAGE_VERSION }}
  
    - name: Push to NuGet
      run: dotnet nuget push "./out/MVVMToolkitExtensions.WPF.*.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
