name: deployment

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet: ['6.0.x', '7.0.x']
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Pack with tag version
      run: |
        $version = "${GITHUB_REF#refs/tags/v}"
        dotnet pack ./src/MVVMToolkitExtensions.WPF/MVVMToolkitExtensions.WPF.csproj --configuration Release -o ./out /p:Version=$version
  
    - name: Push to NuGet
      run: dotnet nuget push "./out/MVVMToolkitExtensions.WPF.*.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
