name: deployment

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Restore dependencies
      run: dotnet restore ./src/AutoWireViewModel/AutoWireViewModel.csproj
      
    - name: Pack core project (without configuration)
      run: dotnet pack ./src/AutoWireViewModel/AutoWireViewModel.csproj -o out

    - name: Restore dependencies
      run: dotnet restore ./src/AutoWireViewModel.WPF/AutoWireViewModel.WPF.csproj
    
    - name: Pack core project (without configuration)
      run: dotnet pack ./src/AutoWireViewModel.WPF/AutoWireViewModel.WPF.csproj -o out
    
    - name: Push to NuGet
      run: dotnet nuget push ./out/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json

